//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50215.44.
// 


/// <remarks/>
[System.Web.Services.WebServiceBindingAttribute(Name="CarBizObjectSoap", Namespace="http://IntertechTraining.com/")]
public partial interface ICarBizObjectSoap {
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://IntertechTraining.com/RemoveCar", 
        RequestNamespace="http://IntertechTraining.com/", 
        ResponseNamespace="http://IntertechTraining.com/", 
        Use=System.Web.Services.Description.SoapBindingUse.Literal, 
        ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    void RemoveCar(int carID);
}
